version: "3.7"
services:
    api:
        image: libraryapi
        depends_on: 
            - sql
            - redis
            - rabbit
        ports: 
            - "5000:80"
        environment:
            - ConnectionStrings__LibraryDatabase=server=sql;database=library;user id=SA;password=Tokyo_Joe
            - ConnectionStrings__Redis=localhost
            - rabbit:HostName=rabbit
            - rabbit:UserName=guest
            - rabbit:Password=guest
            - rabbit:Port=5672
            - rabbit:VHost=/
        networks:
            - my-network
    sql:
        image: shopping-sql
        ports:
            - "1433:1433"
        networks:
            - my-network
    redis:
        image: redis
        ports: 
            - "6379:6379"
        networks: 
            - my-network

    rabbit:
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - my-network
networks:
    my-network:
        driver: bridge